name: Terraform + EKS Deployment

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_WORKING_DIR: .
  AWS_REGION: ap-southeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  # ==========================================
  # STAGE 1: VALIDATE
  # ==========================================
  validate:
    name: ✅ Validate Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.0  # This version is compatible with the Terraform code in this repository required_version = "~> 1.15.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2

      - name: Create PEM file
        run: |
            mkdir -p keys
            echo "${{ secrets.EC2_PRIVATE_KEY }}" > keys/srp.pem
            chmod 600 keys/srp.pem

      - name: 🚀 Terraform Init
        run: terraform init

      - name: 📝 Terraform Format Check
        run: terraform fmt -check

      - name: ✔️ Terraform Validate
        run: terraform validate

  # ==========================================
  # STAGE 2: PLAN
  # ==========================================
  plan:
    name: 📋 Terraform Plan
    runs-on: ubuntu-latest
    needs: validate

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.0  

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2  

      - name: Create PEM file
        run: |
            mkdir -p keys
            echo "${{ secrets.EC2_PRIVATE_KEY }}" > keys/srp.pem
            chmod 600 keys/srp.pem

      - name: 🚀 Terraform Init
        run: terraform init

      - name: 📋 Terraform Plan
        run: terraform plan -out=tfplan

      - name: 📦 Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          retention-days: 7
  # ==========================================
  # STAGE 3: APPLY
  # ==========================================
  apply:
    name: 🚀 Terraform Apply
    runs-on: ubuntu-latest
    needs: plan

    #environment:
      #name: production

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.0  

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2 

      - name: Create PEM file
        run: |
            mkdir -p keys
            echo "${{ secrets.EC2_PRIVATE_KEY }}" > keys/srp.pem
            chmod 600 keys/srp.pem

      - name: 🚀 Terraform Init
        run: terraform init

      - name: 📦 Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Show downloaded files
        run: |
            pwd
            ls -R 

      - name: ✅ Terraform Apply
        run: terraform apply -input=false tfplan

      - name: 📢 Send SNS Notification
        if: success()
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:ap-southeast-2:022499019288:MyEKStopic \
            --subject "Terraform Apply Successful" \
            --message "
            Workflow: ${{ github.workflow }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Run ID: ${{ github.run_id }}

            Terraform apply completed successfully.

            URL:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            "